# System parameters
num_steps: 10
overseer_steps: 5
helpfulness_thresh: 4
harmlessness_thresh: 4

# User and Teacher datasets
user_data_path: './data/harmless-base/test.jsonl'
helpfulness_test_data: './data/helpful-base/test.jsonl'
helpfulness_train_data: './data/helpful-base/train.jsonl'
harmlessness_test_data: './data/harmless-base/test.jsonl'
harmlessness_train_data: './data/harmless-base/train.jsonl'

# Model parameters
model_id: 'mistralai/Mistral-7B-v0.1'
lora_id: rjuggins/instruction_mistral_7b_v1_2_epochs_test
max_length: 1536
hf_key_path: '../keys/hf_key.txt'

bnb_params:
  load_in_4bit: True
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_use_double_quant: False

# Outside expert parameters
expert_model_id: 'gpt-4'
openai_key_path: '../keys/openai_key.txt'
