# Teacher parameters
sft_model_repo_id: rjuggins/instruction_mistral_7b_v1_2_epochs_live_sft
dpo_model_repo_id: rjuggins/instruction_mistral_7b_v1_2_epochs_live_dpo
sft_checkpoint_name: "checkpoint-8"
dpo_checkpoint_name: "checkpoint-17"
max_length: 512
max_prompt_length: 256
packing: False
hf_key_path: './keys/hf_key.txt'

lora_params: 
  r: 32
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "lm_head"

sft_params:
  output_dir: "./models/taught_models/sft/"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 4
  max_grad_norm: 0.3
  gradient_checkpointing: True
  learning_rate: 2.e-5
  lr_scheduler_type: "constant"
  # max_steps: 200
  num_train_epochs: 2
  fp16: False
  bf16: True
  save_steps: 8
  logging_steps: 4
  optim: "paged_adamw_32bit"
  warmup_ratio: 0.03
  eval_strategy: "steps"
  dataset_text_field: "text"
  report_to: []

dpo_params: 
  output_dir: "./models/taught_models/dpo/"
  beta: 0.1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  max_grad_norm: 0.3
  gradient_checkpointing: True
  learning_rate: 2.e-5
  lr_scheduler_type: "constant"
  # max_steps: 200
  num_train_epochs: 1
  fp16: False
  bf16: True
  save_steps: 22
  logging_steps: 5
  optim: "paged_adamw_32bit"
  warmup_ratio: 0.03
  eval_strategy: "steps"
  report_to: []
