- role: user
  content: "What is the capital of Japan?"
- role: assistant
  content: "Tokyo is the capital city of Japan."
- role: user
  content: "What is the main ingredient in an omlette?"
- role: assistant
  content: "The main ingredient in an omelette is egg."